### ISSUE TITLE
installing local tunnel and launching web server

### ISSUE THREAD

**Issue by gsamad0** [gsamad0/pluralsight-js-dev-env#1]
Abdul Samad@DESKTOP-AL4SADN MINGW64 ~/pluralsight-js-dev-env (master)
$ npm install localtunnel -g
C:\Users\Abdul Samad\AppData\Roaming\npm\lt -> C:\Users\Abdul Samad\AppData\Roaming\npm\node_modules\localtunnel\bin\client
+ localtunnel@1.9.2
added 55 packages from 34 contributors in 19.514s

Abdul Samad@DESKTOP-AL4SADN MINGW64 ~/pluralsight-js-dev-env (master)
$ node buildScripts/srcServer.js
internal/modules/cjs/loader.js:626
    throw err;
    ^

Error: Cannot find module 'C:\Users\Abdul Samad\pluralsight-js-dev-env\buildScripts\srcServer.js'
?[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)?[39m
?[90m    at Function.Module._load (internal/modules/cjs/loader.js:527:27)?[39m
?[90m    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)?[39m
?[90m    at internal/main/run_main_module.js:17:11?[39m {
  code: ?[32m'MODULE_NOT_FOUND'?[39m,
  requireStack: []
}

**Comment by coryhouse** [comment]
3 issues:

1. Move .babelrc to the project root (same level as package.json)
2. Change the prestart script to use babel-node:  `"prestart": "babel-node buildScripts/startMessage.js",`
3. Change open:src to use babel-node: `"open:src": "babel-node buildScripts/srcServer.js",`

After that, it starts fine. babel-node is mentioned in this clip: https://app.pluralsight.com/player?course=javascript-development-environment&author=cory-house&name=javascript-development-environment-m6&clip=5&mode=live

**Comment by gsamad0** [comment]
Seen, Thank you.
