### ISSUE TITLE
.babel error issue 

### ISSUE THREAD

**Issue by gsamad0** [gsamad0/pluralsight-js-dev-env#2]
Abdul Samad@DESKTOP-AL4SADN MINGW64 ~/Desktop/pluralsight-js-dev-env (master)
$ npm start

> javascript-development-environment@1.0.0 prestart C:\Users\Abdul Samad\Desktop\pluralsight-js-dev-env
> node buildScripts/startMessage.js

C:\Users\Abdul Samad\Desktop\pluralsight-js-dev-env\buildScripts\startMessage.js:1
import chalk from 'chalk';
       ^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:718:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
    at internal/main/run_main_module.js:17:11
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! javascript-development-environment@1.0.0 prestart: `node buildScripts/startMessage.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the javascript-development-environment@1.0.0 prestart script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Abdul Samad\AppData\Roaming\npm-cache\_logs\2019-06-20T23_13_12_272Z-debug.log

Abdul Samad@DESKTOP-AL4SADN MINGW64 ~/Desktop/pluralsight-js-dev-env (master)
$

**Comment by coryhouse** [comment]
Can you please post on the course discussion instead? When you do, please post a link to your GitHub repo so I can run your code. Thanks!
