### ISSUE TITLE
Got this error in lint. 

### ISSUE THREAD

**Issue by gsamad0** [gsamad0/pluralsight-js-dev-env#3]
Although the color indication is showing, but i am Still getting this below error in my VS terminal and i did follow your direction just as you advised. And yes, there is no .eslintrc in my directory to delete. although it could be because i didn't disable the built one in my text editor (Visual Studio). However, i have know to clue on how to disable it if it is the reason. 

PS: npm start still runs fine. its the crosschecking of lint the isn't.

Thanks

Abdul Samad@DESKTOP-AL4SADN MINGW64 ~/Desktop/pluralsight-js-dev-env (master)
$ npm run lint

> javascript-development-environment@1.0.0 lint C:\Users\Abdul Samad\Desktop\pluralsight-js-dev-env> esw webpack.config.* src buildScripts --color

C:\Users\Abdul Samad\Desktop\pluralsight-js-dev-env\webpack.config.dev.js (0/1)
  !  2:1  Definition for rule 'no console' was not found  no console

C:\Users\Abdul Samad\Desktop\pluralsight-js-dev-env\src\index.js (3/1)
  !  1:1  Definition for rule 'no console' was not found    no console
  ✖  5:7  'courseValue' is assigned a value but never used  no-unused-vars
  ✖  6:1  Unexpected 'debugger' statement                   no-debugger
  ✖  7:1  Unexpected console statement                      no-console

C:\Users\Abdul Samad\Desktop\pluralsight-js-dev-env\buildScripts\srcServer.js (0/1)
  !  1:1  Definition for rule 'no console' was not found  no console

C:\Users\Abdul Samad\Desktop\pluralsight-js-dev-env\buildScripts\startMessage.js (1/1)
  !  1:1  Definition for rule 'no console' was not found  no console
  ✖  3:1  Unexpected console statement                    no-console

✖ 4 errors ! 4 warnings (9:22:28 AM)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! javascript-development-environment@1.0.0 lint: `esw webpack.config.* src buildScripts --color`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the javascript-development-environment@1.0.0 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Abdul Samad\AppData\Roaming\npm-cache\_logs\2019-06-21T08_22_29_121Z-debug.log

Abdul Samad@DESKTOP-AL4SADN MINGW64 ~/Desktop/pluralsight-js-dev-env (master)
$ npm start -s
Starting app in dev mode...
(node:9960) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated

**Comment by coryhouse** [comment]
Typo. Change line 18 in .eslintrc.js to this:

    "no-console": 1

**Comment by gsamad0** [comment]
changed but still having the following error:

C:\Users\Abdul Samad\Desktop\pluralsight-js-dev-env\buildScripts\startMessage.js (0/1)
  !  3:1  Unexpected console statement  no-console

✖ 2 errors ! 2 warnings (5:36:50 PM)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! javascript-development-environment@1.0.0 lint: `esw webpack.config.* src buildScripts --color`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the javascript-development-environment@1.0.0 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Abdul Samad\AppData\Roaming\npm-cache\_logs\2019-06-21T16_36_50_990Z-debug.log

**Comment by coryhouse** [comment]
ESlint is working as expected. You've configured it to not allow console statements (via eslintrc.js). It's pointing out the lines where you're using console.log. 

Add a comment to the top of any file where you're using console.log to supress the warning:

/*eslint-disable no-console */
