### ISSUE TITLE
APPVEYOR ERROR

### ISSUE THREAD

**Issue by gsamad0** [gsamad0/pluralsight-js-dev-env#4]
Travis configuration was successful even though i use a windows OS. However, i got this below error when i commit and push my Appveyor configuration on git:

**> "The build phase is set to "MSBuild" mode (default), but no Visual Studio project or solution files were found in the root directory. If you are not building Visual Studio project switch build mode to "Script" and provide your custom build command."**

please guide me.

thanks.

**Comment by coryhouse** [comment]
Your repo doesn't have an appveyor file

**Comment by coryhouse** [comment]
Note that I show how to create an appveyor config file in the course.
